### ISSUE TITLE
AttributeError: adapters

### ISSUE THREAD

**Issue by zopyx** [ploneintranet/ploneintranet.suite#5]
Creating a Plone site with the Intranet extension profile gives me this:

Traceback (most recent call last):
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in **init**
    response=b)
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/Users/ajung/.buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/Users/ajung/.buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/**init**.py", line 31, in notify
    subscriber(event)
  File "/Users/ajung/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/ajung/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/ajung/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters

**Comment by l34marr** [comment]
I run into the same issue, seemingly caused by old package sources in the src directory. My workaround is to create the fresh Plone 4.3.2 instance, then run buildout with package sources.

For the record: my develop.cfg has the following settings. Hope that's helpful for someone.
[sources]
plone.app.portlets = fs plone.app.portlets
collective.quickupload = fs collective.quickupload
Products.AddRemoveWidget = fs Products.AddRemoveWidget
Products.AutocompleteWidget = fs Products.AutocompleteWidget
collective.disqus = fs collective.disqus
eea.facetednavigation = fs eea.facetednavigation
eea.faceted.vocabularies = fs eea.faceted.vocabularies
eea.jquery = fs eea.jquery
collective.geo.bundle = fs collective.geo.bundle
collective.geo.behaviour = fs collective.geo.behaviour
collective.geo.contentlocations = fs collective.geo.contentlocations
collective.geo.geographer = fs collective.geo.geographer
collective.geo.kml = fs collective.geo.kml
collective.geo.mapwidget = fs collective.geo.mapwidget
collective.geo.openlayers = fs collective.geo.openlayers
collective.geo.settings = fs collective.geo.settings
collective.z3cform.mapwidget = fs collective.z3cform.mapwidget
collective.jsonify = git git@github.com:collective/collective.jsonify.git
